.github/ISSUE_TEMPLATE.md
A ideia desse PR é facilitar a criação de issues no projeto ao utilizar um template.
=> Template de issue para o projeto para facilitar a criação de issues

SUMMARY.md, python/booleanos.md, python/comparando.md, python/dicionarios.md, python/erros.md, python/funcao_print.md, python/introducao.md, python/listas.md, python/resumo_ate_agora.md, python/strings.md, python/variaveis.md
Adicionar parte do capítulo com o conteúdo sobre python. 
Neste em específico:
- Introdução ao python
- Strings
Foi criado uma nova pasta que contém os arquivos sobre:
- introdução
- strings
Foi alterado também o summary para que os links funcionem corretamente.
Verificando se o conteúdo está adequado e se os links no summary foram adicionados corretamente
@lipemorais @Amandasv
=> Capítulo: Python

SUMMARY.md, salve_o_codigo/lacos.md
A ideia desse PR é adicionar a sessão de lacos do tutorial
Adicionei o arquivo em `salve_o_codigo/lacos.md` com o conteúdo da sessão 
@Amandasv @anaschwendler @carolmoers
=> Adiciona parte de laços do salve o código

.github/PULL_REQUEST_TEMPLATE.md
A ideia desse PR é adicionar um PR template para facilitar a descrição das contribuições.
Adicionei o arquivo para que apareça assim que for integrado ao código
@anaschwendler @Amandasv @pedrro @carolmoers @zalbamonteiro
=> Adiciona template para pull requests ao projeto

SUMMARY.md, salve_o_codigo/resumo-sessao.md
A ideia desse PR é adicionar o resumo da sessão salve o código ao tutorial
Adicionei a sessão em `salve_o_código`
@anaschwendler @Amandasv @pedrro @zalbamonteiro @carolmoers
=> Adiciona a sessao de resumo da parte de salve o código

SUMMARY.md, salve_o_codigo/intro.md
A ideia desse PR é adicionar a introdução da sessão "Salve o código!"
Criei o arquivo de introdução e ajustei o sumário
@anaschwendler @Amandasv @pedrro @zalbamonteiro @lipemorais
=> Adicionando intro sessão salve o código

SUMMARY.md, salve_o_codigo/e_se_nao.md, salve_o_codigo/estruturas_condicionais.md, salve_o_codigo/resumo.md
A ideia desse PR é adicionar a parte de estruturas condicionais da sessão "Salve o código!"
Criei ajustei o sumário e adicoinei as partes:
- if...elif...else
- e se não
- resumo
@anaschwendler @Amandasv @pedrro @zalbamonteiro @lipemorais
=> Adicinando estruturas condicionais na sessão Salve o código!

SUMMARY.md, django/o_que_e.md, django/porque_um_framework.md, django/solicitando_o_site.md
A ideia desse PR é adicionar a parte de introdução ao Django
Criei ajustei o sumário e adicoinei as partes:
- O que é django
- Por que você precisa de um framework?
- O que acontece quando alguém solicita um site do seu servidor?
@anaschwendler @Amandasv @pedrro @zalbamonteiro @lipemorais
=> Adicinando introdução ao Django

SUMMARY.md, django/instalacao.md, django/instalacao_introducao.md
A ideia desse PR é adicionar a parte de instalação do Django
Criei ajustei o sumário e adicoinei as partes:
- Instalação - Introdução
- Instalação
@anaschwendler @Amandasv @pedrro @zalbamonteiro @lipemorais
=> Adicionando como instalar o django

README.md
Facilitar a contribuição de outras pessoas
Adicionei ao README.md uma sessão de `Como contribuir`
Dê uma olhada no que foi adicionado ao README e me diz o que achou.
@zalbamonteiro @Amandasv @anaschwendler @pedrro @carolmoers
=> Adicionando o como contribuir ao README.md

django/instalando_banco_de_dados.md, internet/como_funciona.md, linha_de_comando/criando_uma_pasta.md, linha_de_comando/entrando_nas_pastas.md, linha_de_comando/introducao.md, linha_de_comando/resumo.md, python/dicionarios.md, python/introducao.md, python/strings.md, salve_o_codigo/intro.md, salve_o_codigo/resumo-sessao.md
Editar as ocorrências de generos citado ao longo do tutorial. Em algumas partes estava somente no feminino e em outras somente no masculino.
E também aproveitei e fechei a Issue #26 
Revisão de todos os arquivos e atualização
Vendo o diff ;)
Todos
=> Edição de gêneros utilizados

salve_o_codigo/e_se_nao.md, salve_o_codigo/estruturas_condicionais.md, salve_o_codigo/intro.md, salve_o_codigo/suas_proprias_funcoes.md
Achei uns códigos que estavam em inglês e traduzi para português.
@lipemorais @carolmoers @Amandasv
=> Traduzindo código inglês para pt-br

SUMMARY.md, query-set-orm/adicionando_objetos.md, query-set-orm/criando_um_objeto.md, query-set-orm/filtrar_objetos.md, query-set-orm/o_que_e_um_queryset.md, query-set-orm/ordenando_objetos.md, query-set-orm/queryset_e_orm_do_django.md, query-set-orm/shell_do_django.md, query-set-orm/todos_os_objetos.md
Adiciona o capítulo de ORM e QuerySet.
Adicionei o capítulo ao tutorial.
Verificar os arquivos no diff para testar.
Todos podem revisar esse PR.
=> QuerySet e ORM do Django

o_que_e_css.md
=> Criado o_que_e_css.md

vamos_usar_o_bootstrap.md
=> vamos_usar_o_bootstrap.md

instalar_bootstrap.md
=> instalar_bootstrap.md

arquivo_estaticos_no_django.md
__Coloque aqui como isso ajuda o projeto__
__Explique aqui o que foi feito para que isso funcionasse__
__Escreve aqui como a gente poderia testar e ver isso funcionando__
__Quem são as melhores pessoas para revisar esse PR?__
**TODO**
__Caso tenha algo que ainda precisa ser feito crie uma lista aqui__
- [] __exemplo de algo que precisa ser feito__
=> arquivo_estaticos_no_django

salve_o_codigo/suas_proprias_funcoes.md
_só um ajuste na chamada da função que estava em inglês, enquanto a função em si estava em português :)
--
--
todos
=> ajuste no nome da função

SUMMARY.md, css/bootstrap.md, css/css.md, css/estaticos_do_django.md, css/primeiro_arquivo_css.md, vamos_usar_o_bootstrap.md
Adicionar o capítulo de CSS do tutorial
Adicionei cada sessão do capítulo e revisei junto com a @Amandasv 
Verificando os arquivos que foram alterados e adicionados nesse PR
TODOS
**TODO**
=> Capítulo de CSS para o tutorial

SUMMARY.md, css/bootstrap.md, css/css.md, css/estaticos_do_django.md, css/primeiro_arquivo_css.md, estendendo_template/estendendo_templates.md, vamos_usar_o_bootstrap.md
Adicionar o capítulo de estender os templates
Adicionei os arquivos para essa sessão no tutorial
Verifique os arquivos adicionados
TODOS
=> Capítulo de estender templates

SUMMARY.md, amplie_sua_aplicacao/amplie_sua_aplicacao.md
Adiciona o capítulo de ampliar a aplicação
Adicionei os arquivos referentes ao capítulo e atualizei o que precisava
Verificando os arquivos adicionados e alterados
TODOS
**TODO**
=> Adiciona o capítulo 'Ampliando sua aplicação'

SUMMARY.md, formularios/editando_formularios.md, formularios/introducao.md, formularios/salvando_formularios.md, formularios/seguranca.md, formularios/template.md, formularios/url_e_views.md, formularios/validacao_formularios.md
Adicionar o capítulo de formulários
Adicionei o conteúdo do capítulo de formulários
Verificando o conteúdo do diff e os arquivos adicionados
TODOS
**TODO**
=> Adicinoa o capítulo de Formulários

python/comparando.md, python/dicionarios.md, python/erros.md, python/introducao.md, python/variaveis.md, salve_o_codigo/intro.md
Realizar alguns ajustes necessários no texto.
=> #27 - ajustes textos necessários

SUMMARY.md, o_que_vem_depois/o_que_vem_depois.md
Adiciona o último capítulo do tutorial
Adicionei o capítulo com seu conteúdo
Verificar os arquivos no tutorial
TODOS
=> Adiciona o capítulo de o que vem depois ao tutorial

python/comparando.md
Como uma sugestão feita pelo @machadowisck estou sugerindo a remoção dessa frase já que não damos esse tipo de exemplo nessa parte do tutorial.
Removi a frase.
Dando uma olhada no que foi alterado.
@machadowisck e outras pessoas que quiserem ajudar.
=> Remove a frase de comparação de métodos já que não damos nenhum exempo

python/variaveis.md
Mudar de `Vê` para `Viu`, uma sugestão do @machadowisck
Mudei ali a palavra
Só dar uma olhada ali no diff
@machadowisck ou qualquer outra pessoa que possa ajudar.
=> Muda a expressão Vê para Viu por ser melhor em português

query-set-orm/filtrar_objetos.md
Corrigir pequenos problema no capítulo de filtros do queryset
Fiz as correções no arquivo `filtrar_objetos`
Só dar uma olhadinha ali no diff
TODOS
=> Realiza pequenas correções no capítulo

introducao_html/customizacao.md
Corrigir o nome do blog para algo em português
Corrigi o nome ali no arquivo de customização
Só olhar o diff ali
TODOS
=> Corrige o nome do blog

linha_de_comando/pasta_atual.md, python/strings.md, salve_o_codigo/estruturas_condicionais.md
- Adicionar tradução e  substituir alguns termos em inglês
- Adicionar barra invertida que não estava aparecendo
- Foram realizadas a tradução e substituição dos termos;
- Foi adicionada a barra invertida
- Verificar tradução de "print working directory" em "pastas_atual";
- Verificar substituição de "It Works!" para "Isso Funciona!" em "estruturas_condicionais'"
- Verificar se a barra invertida está sendo exibida em "strings"
__Quem são as melhores pessoas para revisar esse PR?__
**TODO** …
=> Adicionar traducão

estendendo_templates/estendendo_templates.md
Arrumar o capítulo de estender templates
Mudança nos arquivos correspondentes
Verificando os arquivos alterados
@Amandasv
=> corrige capítulo de estender templates

book.json
Adiciona uma key do google analytics para que possamos ter informações sobre como as pessoas acessam o nosso site.
Com o google analytics podemos ter algumas métricas sobre o tutorial, algumas delas:
numero de visualizações do tutorial
tempo médio das pessoas fazendo o tutorial
até aonde as pessoas costumam fazer o tutorial
Mergear o PR, acessar a conta do google analytics e verificar se o site aparece lá.
=> #64 - adiciona key do google analytics
